spring:
  h2:
    console:
      enabled: true
  application:
    name: project
  datasource:
    url: jdbc:h2:mem:testdb?currentSchema=public;NON_KEYWORDS=VALUE, TYPE, USER, NAME
    username: sa
    password: postgres
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
      show_sql: true
  main:
    allow-bean-definition-overriding: true
tech-challenge:
  client-id: tech-challenge
  client-secret: lEF2yPgUrI57mSQyhPZTH1VuxUrMS1tx
  payments:
    base-url: http://localhost:8081
  order:
    base-url: http://localhost:8081
keycloak:
  base-url: http://localhost:29000
logging:
  level:
    root: INFO
mercado-pago:
  access-token: TEST-6546844616028207-063020-f09a0b6563261874ab236fd560e23d9b-769812162
  user-id: 769812162
  pos: SUC001POS002