spring:
  application:
    name: project
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=payments}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      globally_quoted_identifiers: true
      show_sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: tech-challenge-kitchen
            client-secret: Dfry1oV4dQDHZ9mzIuCxAhiOL1Aav20Y
            authorization-grant-type: client-credentials
            scope: openid, profile, email
            redirect-uri: ${KEYCLOAK_BASE_URL}/login/oauth2/code/keycloak
            client-name: Kitchen
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_BASE_URL}/realms/master/protocol/openid-connect/token
            authorization-uri: ${KEYCLOAK_BASE_URL}/realms/master/protocol/openid-connect/auth
            user-info-uri: ${KEYCLOAK_BASE_URL}/realms/master/protocol/openid-connect/userinfo
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL}/realms/master
  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy=ant_path_matcher:logging:
  level:
    root: INFO
tech-challenge:
  client-id: tech-challenge-payments
  client-secret: "**********"
  payments:
    base-url: ${TECH_CHALLENGE_PAYMENT_BASE_URL:http://localhost:8081}
  order:
    base-url: ${TECH_CHALLENGE_ORDER_BASE_URL:http://localhost:8082}
keycloak:
    base-url: http://localhost:29000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
