apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge-kitchen-hpa
  namespace: default-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tech-challenge-kitchen-deployment  # ✅ Nome correto do Deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
