apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-kitchen-service
  namespace: default-namespace
spec:
  selector:
    app: tech-challenge-kitchen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30010
  type: LoadBalancer