apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-kitchen-service
  namespace: default-namespace
spec:
  selector:
    app: tech-challenge-kitchen
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort