apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-kitchen-service
  namespace: default-namespace
spec:
  selector:
    app: tech-challenge-kitchen
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: LoadBalancer