apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-kitchen-deployment
  namespace: default-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-kitchen
  template:
    metadata:
      labels:
        app: tech-challenge-kitchen
    spec:
      containers:
        - name: tech-challenge-kitchen
          image: matheuspatricio0/ms-kitchen:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: jdbc:postgresql://mskitchendb.caetpmx4dios.us-east-1.rds.amazonaws.com/postgres?currentSchema=public
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: KEYCLOAK_BASE_URL
              value: http://a3324cb770adc4cc5903a935349dde87-370143530.us-east-1.elb.amazonaws.com
